---
dependency:
  name: galaxy
lint: yamllint . && ansible-lint -x 106 -x 204
driver:
  name: delegated
  options:
    login_cmd_template: 'docker exec -ti {instance} bash'
    ansible_connection_options:
      ansible_connection: docker
platforms:
  - name: instance
    image: geerlingguy/docker-centos8-ansible:latest
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
provisioner:
  name: ansible
  connection_options:
    ansible_connection: docker
verifier:
  name: ansible
